### ISSUE TITLE
After saving and loading world, Actor and Item creation / editing descriptions breaks

### ISSUE THREAD

**Issue by monsterfurby** [Sk1mble/fate-core-official#51]
Version: current (4.4.45), Foundry Build 308 Version 11 Stable
Steps to reproduce: Create blank world, either import base data or none. Create character. Note that character creation works. Shutdown and restart server. Reattempt creating character - this should yield a "Cannot read properties of undefined (reading 'length')" error.

The error is triggered whenever the server attempts to save new entity data, for example upon editing an Actor's "notes" field or creating a new Actor or Item. 

This might be a client-side issue, though I have noticed this happening independently of the game's folder (drive root and userdate) and on both Win10 and MacOS.

I have verified that this seems to be specific to the Fate Core Official system, other systems do not encounter this issue.

Example error (case of creating new Actor):

```
foundry.js:68147 Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68147
commons.js:8047 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Preprocessor.advance (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/sanitization.mjs:1:1235)
    at Actor._sanitizeFields (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:7638)
    at async Actor._sanitizeFields (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:7854)
    at async Actor._sanitizeFields (/F:/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:7854)
```

**Comment by Sk1mble** [comment]
Hi, I consulted with the Foundry dev team, and they said:

[image: image.png]
